# Generated by Django 4.2.6 on 2023-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_uz', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
                ('category_name_en', models.CharField(max_length=50, verbose_name='Category name')),
                ('category_name_ru', models.CharField(max_length=50, verbose_name='Imya kategoriya')),
            ],
            options={
                'db_table': 'foods_categories',
                'ordering': ['category_name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name_uz', models.CharField(max_length=50, verbose_name='Taom nomi')),
                ('food_name_en', models.CharField(max_length=50, verbose_name='Food name')),
                ('food_name_ru', models.CharField(max_length=50, verbose_name='Imya blyuda')),
                ('food_price', models.IntegerField(verbose_name='Narx/Price (so`m)')),
                ('food_image', models.ImageField(upload_to='foods')),
            ],
            options={
                'db_table': 'foods_foods',
                'ordering': ['food_name_uz'],
            },
        ),
    ]
